name: CI - Install

on:
  push:
    branches: [main]

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Homebrew
        run: brew update

      - name: Build from source
        run: |
          brew tap cmccomb/okso https://github.com/cmccomb/okso
          brew install --HEAD cmccomb/okso/okso

      - name: Run formula tests
        run: |
          brew test okso
          okso --version

      - name: Uninstall formula
        run: brew uninstall okso
