name: CI - Install

on:
  push:
    branches: [main]
  pull_request:

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Homebrew
        run: brew update

      - name: Audit formula
        run: brew audit --strict --online ./Formula/okso.rb

      - name: Build from source
        run: brew install --build-from-source ./Formula/okso.rb

      - name: Run formula tests
        run: |
          brew test okso
          okso --version

      - name: Uninstall formula
        run: brew uninstall okso
